name: streamlit-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Specify Python 3.8
  - beautifulsoup4
  - googletrans==4.0.0-rc1
  - deep-translator
  - pip
  - spacy
  - pip:
      - streamlit==1.38.0
      - snowflake-connector-python==3.12.2
      - snowflake-snowpark-python==1.22.1
      - snowflake-ml-python==1.6.2
      - snowflake.core==0.12.1
     # - snowflake.cortex==0.42.1
      - transformers==4.44.2
      # Add any additional pip packages here
      - beautifulsoup4
      - googletrans==4.0.0-rc1
      - deep-translator
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.0/en_core_web_sm-3.7.0-py3-none-any.whl
